element_watch/config/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'', include('watcher.urls'))
]

element_watch/watcher/urls.py
from django.conf.urls import url

from . import views


app_name = 'watcher'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^watched-element/(?P<pk>\d+)/$', views.WatchedElementDetailView.as_view(), name='watched_element_detail'),
    url(r'^watched-element/(?P<pk>\d+)/update/$', views.WatchedElementUpdateView.as_view(), name='watched_element_update'),
    url(r'^watched-element/create/', views.WatchedElementCreateView.as_view(), name='watched_element_create'),
    url(r'^cb/', views.cb_test, name='cb_test'),  # for testing
]

element_watch/watcher/models.py
import datetime

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse


class WatchedElement(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    url = models.URLField()
    html_element = models.CharField(max_length=200, help_text='Css selector for the element to watch.')
    element_value = models.TextField(blank=True, null=True)
    check_interval_hours = models.FloatField(default=1.0, help_text='The interval to check html element in hours.')
    cur_task_id = models.CharField(max_length=36, null=True, blank=True, help_text='Celery task id')
    callback_url = models.URLField()
    last_checked = models.DateTimeField(
        default=timezone.now,
        help_text='Last time the html element was checked for changes.'
    )

    def get_absolute_url(self):
        return reverse('watcher:watched_element_detail', args=[str(self.id)])

    def next_scheduled_update(self):
        return self.last_checked + datetime.timedelta(hours=self.check_interval_hours)

    def __str__(self):
        return f'{self.user} ({self.html_element})'

element_watch/watcher/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt

from .models import WatchedElement
from .tasks import check_html_element_task
from config import celery_app


@login_required
def home(request):
    context = {
        'watched_elements': WatchedElement.objects.filter(user=request.user)
    }
    return render(request, 'watcher/home.html', context=context)


class WatchedElementDetailView(LoginRequiredMixin, generic.DetailView):
    model = WatchedElement

    def get_object(self, queryset=None):
        return get_object_or_404(WatchedElement, id=self.kwargs['pk'], user=self.request.user)


class WatchedElementCreateView(LoginRequiredMixin, generic.CreateView):
    model = WatchedElement
    fields = ['url', 'html_element', 'check_interval_hours', 'callback_url']
    template_name = 'watcher/watchedelement_create_form.html'
    success_url = reverse_lazy('watcher:home')

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        task = check_html_element_task.delay(form.instance.id)
        form.instance.cur_task_id = task.id
        return super().form_valid(form)


class WatchedElementUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = WatchedElement
    fields = ['url', 'html_element', 'check_interval_hours', 'callback_url']
    template_name = 'watcher/watchedelement_update_form.html'
    success_url = reverse_lazy('watcher:home')

    def form_valid(self, form):
        celery_app.control.revoke(form.instance.cur_task_id)
        task = check_html_element_task.delay(form.instance.id)
        form.instance.cur_task_id = task.id
        return super().form_valid(form)


@csrf_exempt
def cb_test(request):
    print('cb info:', request.POST)
    return JsonResponse({'status': 'success'})

element_watch/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Element Watcher</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static '/css/styles.css' %}">
  <script src="{% static '/js/main.js' %}"></script>
</head>

<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="text-center side-bar list-unstyled">
          <li><a href="{% url 'watcher:home' %}">home</a></li>
          <li><a href="https://github.com/caleblogan/html-element-watcher">github</a></li>
          <hr/>
        {% if user.is_authenticated %}
          <li class=""><p>{{ user }}</p></li>
          <li class=""><a id="logout" href="/accounts/logout/" class="btn btn-outline-success">Logout</a></li>
        {% else %}
          <li><a id="twitter_login" href="/accounts/twitter/login?process=login" class="btn btn-outline-success">Sign in with Twitter</a></li>
        {% endif %}
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
      </div>
    </div>

  </div>
</body>
</html>

element_watch/templates/watcher/home.html
{% extends 'base.html' %}

{% block content %}
<h1>Watched Elements</h1>
<hr>
<a href="{% url 'watcher:watched_element_create' %}"><button class="btn btn-outline-primary">Watch New Element</button></a>
<br>
<br>
{% for element in watched_elements %}

  <ul class="list-unstyled">
    <li class="watched-element">
      <h5>
        {{ element.url }}
        <a href="{% url 'watcher:watched_element_update' element.id %}">edit</a>
      </h5>
      <p>Next update: {{ element.next_scheduled_update }}</p>
      <p>Css Selector: {{ element.html_element }} </p>
      <p>Value: {{ element.element_value}} </p>
    </li>
    <hr>
  </ul>

{% endfor %}
{% endblock content %}

element_watch/templates/watcher/watchedelement_create_form.html
{% extends 'base.html' %}

{% block content %}
<h1>Create Watched Elements</h1>
<hr>
<form method="post">{% csrf_token %}
  {{ form.as_p }}
  <button class="btn btn-primary">save</button>
</form>

{% endblock content %}

element_watch/templates/watcher/watchedelement_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>Watched Element</h1>
<hr>

<h5>
  {{ object.url }}
</h5>
<p>Next update: {{ object.next_scheduled_update }}</p>
<p>Xpath: {{ object.html_element }} </p>
<p>Value: {{ object.element_value}} </p>

{% endblock content %}

element_watch/templates/watcher/watchedelement_update_form.html
{% extends 'base.html' %}

{% block content %}
<h1>Update Watched Element</h1>
<hr>

{% load crispy_forms_tags %}
<form method="post">{% csrf_token %}
  {{ form|crispy }}
  <button class="btn btn-primary">save</button>
</form>

{% endblock content %}